//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string ABILITYLEVEUP = "AbilityleveUp";
        public const string BOMB = "Bomb";
        public const string COIN = "Coin";
        public const string DIE = "Die";
        public const string ENEMYDIE = "EnemyDie";
        public const string EXP = "Exp";
        public const string GAMEPOSS = "GamePoss";
        public const string GETALLEXP = "GetAllExp";
        public const string HIT = "HIt";
        public const string HP = "Hp";
        public const string HUIT = "Huit";
        public const string LEVELUP = "LevelUp";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverpanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamepanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePasspanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
}
